### ISSUE TITLE
Üye arayüzünde doğduğu ilçe alanı boş geliyor

### ISSUE THREAD

**Issue by erensenelmis** [TMMOB-BMO/TOYS#116]

**Comment by osmanalper** [comment]
Veritabaninda ilce alani setlenmemis kullanicilarda bu durum olusuyor. Ilce alani setli kullanicida alanin dolu geldigi gozlendi.

![screen shot 2015-03-18 at 19 19 46](https://cloud.githubusercontent.com/assets/4021667/6714958/fe5da736-cda3-11e4-9d21-11f2f60d2f38.png)
